### PR TITLE
Merge changes from modularization-main into modularization/frontend

### PR DESCRIPTION
**Pull request by nikpodsh**
Merge changes from modularization-main into modularization/frontend

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by itsmo-amzn** [comment]
@nikpodsh why there are many files deleted in the frontend?
I thought we're merging/syncing non-frontend changes into this modularization/frontend branch, and since this is a modularization effort, this means no functional changes.

**Comment by nikpodsh** [comment]
@itsmo-amzn, the files that have been deleted are no longer used. Some of those files are just a dead code API, some have been deleted while removing Redshift functionality. These deletion should not bring any functional changes.

**Comment by dbalintx** [comment]
I did a rough review:

Confirmed that changes/diffs are coming from:

- directly from the work that has been done for the backend modularization (changes were reviewed PR by PR)
- through the [modularization-main update with V1.5](https://github.com/awslabs/aws-dataall/commit/07ffa1ba22c5bf0331b5cc75550277f3ff172694)

Changes/diffs to Frontend:

- **non-functional:** removal of unused code, identified by unused graphql calls (for which the backend mutations, queries etc. were also removed), eg. [Redshift removal](https://github.com/awslabs/aws-dataall/pull/551)
- **non-functional:** tracking of enabled/disabled modules via environmental parameters caused some minor changes in FE [(eg.)](https://github.com/awslabs/aws-dataall/commit/f2505b5e4f82c943cf78c6c3f55a9026965c3a8c#diff-68e78b496d65c7dc6b4c719f34a2841bfd2b14b6625ba8a64e769d2a302cd654)
- **functional:** through the [modularization-main update with V1.5](https://github.com/awslabs/aws-dataall/commit/07ffa1ba22c5bf0331b5cc75550277f3ff172694) for eg. the automatic creation of the pivot role through CDK
- **functional:** some FE changes were introduced in [MLstudio modularization](https://github.com/awslabs/aws-dataall/pull/486)

**Comment by itsmo-amzn** [comment]
@dbalintx We had a meeting last Friday with Nikita to go over the merge changes. We ended-up creating an updated merge PR with the latest changes. We ran it locally, and all services seem to be working. we also smoke-tested it.
This is the new merge PR: https://github.com/awslabs/aws-dataall/pull/576

**Pull request closed without merging**
