### PR TITLE
Fix Env Parameters Migration Script

### PR DESCRIPTION
**Pull request by noah-paige**
### Feature or Bugfix

- Bugfix

### Detail
- Resolve errors in migration script for environemnt parameters when upgrading from data.all v1.6.2 with pre-existing environments to beta-2.0

### Relates
- #691 

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by noah-paige** [comment]
Also tested the following to migrations (`92bdf9efb1aa` and `4a0618805341`) for upgrade and downgrade and all looks good

**Comment by noah-paige** [comment]
Received a `ValueError: too many values to unpack (expected 2)` on the migration script now for Line 230 in `migrate_groups_permissions()` function

Not sure I understand what permissions we are trying to check for / what permissions we are trying to add in this migration script

**Comment by noah-paige** [comment]
@nikpodsh , @dbalintx , @dlpzx  - take a look a feel free to update the PR further as needed to resolve the issues seen with backwards compatibility

**Comment by dlpzx** [comment]
HI @noah-paige I confirm the issue :( Let me have a look at the PR

**Review by noah-paige — COMMENTED** [review]
looks good and tested in AWS Deployment

**Review by dlpzx — APPROVED** [review]

**Pull request merged**
