### PR TITLE
Add callback and dependency matrix useclient

### PR DESCRIPTION
**Pull request by noah-paige**
### Feature or Bugfix

- Bugfix

### Detail
- On some updates React is not rendering the `setReAuth()` function in `useClient.js:useEffect()` and thus the ReAuth Modal is never showing after returning a 401 error from the backend

- To remediate
  - Added `setReAuth` as part of the useEffect depedencies
  - Added callback to `setReAuth` to prevent infinite loop of re-rendering the function

### Security
N/A
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by noah-paige** [comment]
Tested in an AWS Deployment and re-auth functionality still working as expected

**Review by dlpzx — APPROVED** [review]

**Comment by dlpzx** [comment]
Can we close this PR? @noah-paige

**Comment by noah-paige** [comment]
@dlpzx I would propose we keep this open and merge into `main` - while the ReAuth components still function without the changes here it resolves some of the warnings coming from `npm run lint` and I think helps with readability of the code to explicitly be setting the proper dependency matrices

Let me know your thoughts

**Comment by dlpzx** [comment]
I think we should then merge it to `main`

**Pull request merged**
