### PR TITLE
Make hosted_zone_id optional, code update

### PR DESCRIPTION
**Pull request by lorchda**
### Feature or Bugfix
- Bugfix

### Detail
- Make `hosted_zone_id` optional, code update

### Relates
- #797 

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?  N/A
  - Is the input sanitized? N/A
  - What precautions are you taking before deserializing the data you consume? N/A
  - Is injection prevented by parametrizing queries? N/A
  - Have you ensured no `eval` or similar functions are used? N/A
- Does this PR introduce any functionality or component that requires authorization? N/A
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms? N/A
  - Are you logging failed auth attempts? N/A
- Are you using or adding any cryptographic features? N/A
  - Do you use a standard proven implementations? N/A
  - Are the used keys controlled by the customer? Where are they stored? N/A
- Are you introducing any new policies/roles/users? N/A
  - Have you used the least-privilege principle? How? N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. YES

### Description

Make `hosted_zone_id` optional and provide `HostedZoneId` and `DNSName` in CloudFormation Stack Output, so users can create their own [Route53 AliasTarget](https://docs.aws.amazon.com/Route53/latest/APIReference/API_AliasTarget.html).

Following validation checks in `ecs_patterns.ApplicationLoadBalancedFargateService` were considered:
* `frontend_alternate_domain` and `userguide_alternate_domain` have to be `None` when the `hosted_zone` is `None`, see checks in [multiple-target-groups-service-base.ts#L463](https://github.com/aws/aws-cdk/blob/c445b8cc6e20d17e4a536f17262646b291a0fe36/packages/aws-cdk-lib/aws-ecs-patterns/lib/base/network-multiple-target-groups-service-base.ts#L463), or else a `A Route53 hosted domain zone name is required to configure the specified domain name` error is raised
* for a HTTPS ALB listener, only the `certificate` is ultimately required, and not the `domainName` or `domainZone`, as per evaluation logic in [application-load-balanced-service-base.ts#L509](https://github.com/aws/aws-cdk/blob/c445b8cc6e20d17e4a536f17262646b291a0fe36/packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L509)

### CODE REVIEW

**Comment by lorchda** [comment]
This is what the [documentation](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/ApplicationLoadBalancedFargateService.html) says for the parameters to `ecs_patterns.ApplicationLoadBalancedFargateService`:

* domain_name (Optional[str]) – The domain name for the service, e.g. “api.example.com.”.
  Default: - No domain name.
* domain_zone (Optional[IHostedZone]) – The Route53 hosted zone for the domain, e.g. “example.com.”.
  Default: - No Route53 hosted domain zone.

**Comment by dlpzx** [comment]
Hi @lorchda, I am looking into this PR today. The albfront stack will only be deployed for VPC-facing frontend. In our documentation we specify that the custom_domain MUST be specified for this type of deployment. 

image

From the code I think there is going to be an issue in lines 149-159

**Comment by lorchda** [comment]
@dlpzx yes noticed that as well. My thinking was that `custom_domain['hosted_zone_name']` would raise a not very descriptive `KeyError` along with a stack trace, but would otherwise abort as desired. This could be improved by providing a user-friendly error message that checks for the presence of `custom_domain['hosted_zone_name']`.

However, this is an unrelated issue that already existed *before* this PR. This PR is related only to `hosted_zoned_id`, and the semantics around `hosted_zone_name` (which *must* be provided) remains the same.

Example configuration:

```json
    "DeploymentEnvironments": [
      {
        "internet_facing": false,
        "custom_domain": {
          "hosted_zone_name": "dataall.example.internal",
          "certificate_arn": "arn:aws:acm:REGION:ACCOUNT_ID:certificate/UID"
        }
        ...
      }
    ]
```

**Comment by lorchda** [comment]
`custom_domain['hosted_zone_name']`
raises a `KeyError` when the key does not exist

`custom_domain.get('hosted_zone_name')`
returns `None` if the key does not exist

**Comment by dlpzx** [comment]
Hi @lorchda, thanks for the quick response. It is true that the certificate problem is more of a cosmetic issue, but based on our experience with customers we really need to provide an error message to users for them to understand the issue. This problem was not there before because `custom_domain['hosted_zone_name']` was mandatory (at least in the documentation) for an internet_facing=false.

It is still unclear to me what your final architecture looks like. The target is to not provide any route53 zone or certificate and have the ALB defined without those optional parameters right? In your cdk.json the parameter `"custom_domain"` does not exist right?

**Comment by lorchda** [comment]
@dlpzx I added a fix for this (unrelated) issue to check for `custom_domain['hosted_zone_name']`

**Comment by dlpzx** [comment]
Thank you @lorchda, the PR looks good. I will do a final test by deploying it to AWS and we can merge

**Review by dlpzx — APPROVED** [review]

**Pull request merged**
